# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/list-emails
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

name: Validate Docs

# Run Workflow for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_markdown:
    name: Lint Markdown files
    runs-on: "ubuntu-latest"
    # Default: 360 minutes
    timeout-minutes: 10

    steps:
      - name: Setup Node
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "10.x"

      - name: Install Markdown linting tools
        run: |
          npm install markdownlint --save-dev
          npm install -g markdownlint-cli

      - name: Check out code
        uses: actions/checkout@v2.3.3

      - name: Run Markdown linting tools
        # The `.markdownlint.yml` file specifies config settings for this
        # linter, including which linting rules to ignore.
        #
        # Note: Explicitly ignoring top-level vendor folder; we do not want
        # potential linting issues in bundled documentation to fail linting CI
        # runs for *our* documentation
        run: |
          markdownlint '**/*.md' --ignore node_modules --ignore vendor
